CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: 'pose_resnet'
MODEL: 'multi_person_posenet'
DATA_DIR: ''
GPUS: '0'
OUTPUT_DIR: 'output/511'
LOG_DIR: 'output/511'
WORKERS: 8
PRINT_FREQ: 500

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'demo'
  TEST_DATASET: 'demo'
  DATA_FORMAT: png
  DATA_AUGMENTATION: False
  FLIP: False
  ROOT: 'data/ZJUMocap-511/' # 'data/panoptic/'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'demo'
  TRAIN_SUBSET: 'demo'
  ROOTIDX: 2
  CAMERA_NUM: 4
NETWORK:
  PRETRAINED_BACKBONE: "models/pose_resnet50_coco_rh_1.4.pth"
  PRETRAINED:  ''  # 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 512
  - 384
  HEATMAP_SIZE:
  - 128
  - 96
  SIGMA: 3
  NUM_JOINTS: 15
  USE_GT: False
POSE_RESNET:
  FINAL_CONV_KERNEL: 1
  DECONV_WITH_BIAS: False
  NUM_DECONV_LAYERS: 3
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_DECONV_KERNELS:
  - 4
  - 4
  - 4
  NUM_LAYERS: 50
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 50
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
TEST:
  MODEL_FILE: 'model_best.pth.tar'
  BATCH_SIZE: 1
DEBUG:
  DEBUG: false
  SAVE_BATCH_IMAGES_GT: false
  SAVE_HEATMAPS_GT: false
  SAVE_HEATMAPS_PRED: false
MULTI_PERSON:
  # SPACE_SIZE:
  #   - 8000.0
  #   - 8000.0
  #   - 2000.0
  # SPACE_CENTER:
  #   - 0.0 # 120.0
  #   # - -500.0 # -600.0
  #   - 0.0 # -600.0
  #   - 800.0
  SPACE_SIZE:
    - 4000.0
    - 4000.0
    - 2000.0
  SPACE_CENTER:
    - 0.0 # 120.0
    # - -500.0 # -600.0
    - 0.0 # -600.0
    - 1000.0
  INITIAL_CUBE_SIZE:
    - 80
    - 80
    - 20
  MAX_PEOPLE_NUM: 10
  THRESHOLD: 0.3
PICT_STRUCT:
  GRID_SIZE:
    - 2000.0
    - 2000.0
    - 2000.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
